#!/usr/bin/env bash
# scripts/write-env-local.sh — .env.local 의 DATABASE_URL / DIRECT_URL 만 갱신.
# 다른 키는 보존 (사용자가 추가한 로컬-only 오버라이드 등).
#
# Next.js 우선순위: .env.local > .env.development > .env. 즉 .env 의 원격 값을 가려서
# 로컬 Postgres 로 라우팅. Prisma CLI 는 .env.local 을 안 읽으므로, prisma 호출 시
# set-workspace-env-vars.sh 를 source 해서 env 직접 주입할 것 (scripts/db-container/migrate-deploy.sh 등 참조).

set -euo pipefail

if [ -z "${DATABASE_URL:-}" ]; then
  # shellcheck disable=SC1091
  source "$(dirname "$0")/set-workspace-env-vars.sh"
fi

ENV_FILE=".env.local"
TMP="$(mktemp)"

if [ -f "$ENV_FILE" ]; then
  # 기존 파일의 우리 키 + AUTO-GENERATED 헤더 제거 → 다른 키 보존
  grep -vE '^(DATABASE_URL|DIRECT_URL)=|^# AUTO-GENERATED|^# Worktree:' "$ENV_FILE" > "$TMP" || true
fi

{
  echo "# AUTO-GENERATED by pnpm workspace:setup — do not edit DATABASE_URL/DIRECT_URL here."
  echo "# Worktree: $WORKTREE_NAME / Port: $POSTGRES_HOST_PORT"
  echo "DATABASE_URL=$DATABASE_URL"
  echo "DIRECT_URL=$DIRECT_URL"
} >> "$TMP"

mv "$TMP" "$ENV_FILE"
echo "[db] Wrote $ENV_FILE (port=$POSTGRES_HOST_PORT)"
